name: Build packages

inputs:
  name:
    required: true
    type: string
  nightly:
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Set version information from tag
      if: ${{ inputs.nightly == false }}
      uses: ./.github/actions/set_version_from_tag

    - name: Set OS-specific variables
      shell: bash
      run: |
        if [[ "${{ inputs.name }}" == ubuntu-* || "${{ inputs.name }}" == debian-* ]]; then
          echo "PKG_TYPE=deb" >> "$GITHUB_ENV"
        elif [[ "${{ inputs.name }}" == centos-* ]] ; then
          echo "PKG_TYPE=rpm" >> "$GITHUB_ENV"
        else
          echo "Bad inputs.name: ${{ inputs.name }}"
          exit 1
        fi

    - name: Check out rspamd
      uses: actions/checkout@v4
      with:
        repository: rspamd/rspamd
        path: rspamd
        ref: master

    - name: Check out packpack
      uses: actions/checkout@v4
      with:
        repository: packpack/packpack
        path: packpack

    - name: Build packages
      shell: bash
      run: |
        export ASAN=0
        export BUILDDIR=${{ github.workspace }}/build
        export DEBIAN=0
        export DOCKER_IMAGE=${{ inputs.name }}
        export DOCKER_REPO=ghcr.io/rspamd/rspamd-build-docker
        export LUAJIT=1
        export PRESERVE_ENVVARS=LUAJIT,ASAN
        export RELEASE=$RELEASE_VERSION
        export RPM=0
        export VERSION=$RSPAMD_VERSION

        mkdir $BUILDDIR
        echo "BUILDDIR=${BUILDDIR}" >> "$GITHUB_ENV"

        if [[ "${{ env.PKG_TYPE }}" == "deb" ]]; then
          export DEBIAN=1
        elif [[ "${{ env.PKG_TYPE }}" == "rpm" ]]; then
          export RPM=1
        else
          echo "Bad env.PKG_TYPE: ${{ env.PKG_TYPE }}"
          exit 1
        fi

        cd rspamd
        ../packpack/packpack
        if [ $RPM -eq 1 ]; then
          export ASAN=1
          ../packpack/packpack
        fi

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ runner.arch }}-${{ inputs.name }}
        path: |
          ${{ env.BUILDDIR }}/*.deb
          ${{ env.BUILDDIR }}/*.rpm
        retention-days: 1
        compression-level: 0
