name: Test package

inputs:
  name:
    required: true
    type: string
  platform:
    required: true
    type: string
  run_id:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Download package
      uses: actions/download-artifact@v5
      with:
        name: packages-${{ inputs.platform }}-${{ inputs.name }}
        run-id: ${{ inputs.run_id || github.run_id }}

    - name: Perform OS-specific steps
      shell: bash
      run: |
        # Install rspamd
        if [[ "${{ inputs.name }}" == ubuntu-* || "${{ inputs.name }}" == debian-* ]]; then
          apt-get update
          apt-get install -f -y ./rspamd_*deb ./rspamd-dbg_*deb
        elif [[ "${{ inputs.name }}" == centos-10 ]] ; then
          dnf config-manager --set-enabled ol10_codeready_builder
          dnf -qy install oracle-epel-release-el10
        elif [[ "${{ inputs.name }}" == centos-9 ]] ; then
          dnf -qy install epel-release
          dnf config-manager --set-enabled ol9_codeready_builder
        elif [[ "${{ inputs.name }}" == centos-8 ]] ; then
          dnf -qy install epel-release
          dnf config-manager --set-enabled ol8_codeready_builder
        else
          echo "Bad inputs.name: ${{ inputs.name }}"
          exit 1
        fi

        if [[ "${{ inputs.name }}" == centos-* ]]; then
          dnf install rspamd-[0-9]*4.rpm rspamd-debuginfo-[0-9]*4.rpm
        fi

        # Install test dependencies
        if [[ "${{ inputs.name }}" == ubuntu-* || "${{ inputs.name }}" == debian-* ]]; then
          apt-get install -y python3 python3-dev python3-nacl python3-pip python3-psutil python3-tornado python3-venv redis-server
        elif [[ "${{ inputs.name }}" == centos-* && "${{ inputs.name }}" != centos-10 ]]; then
          dnf install -y gcc git python3 python3-devel python3-pip redis
        elif [[ "${{ inputs.name }}" == centos-10 ]]; then
          dnf install -y gcc git python3 python3-devel python3-pip valkey
          ln /usr/bin/valkey-server /usr/bin/redis-server
          ln /usr/bin/valkey-cli /usr/bin/redis-cli
        fi

    - name: Set version information
      uses: ./.github/actions/set_version

    - name: Check out rspamd
      uses: actions/checkout@v4
      with:
        repository: rspamd/rspamd
        path: rspamd
        ref: "${{ env.RSPAMD_VERSION }}"

    - name: Set up test environment
      shell: bash
      run: |
        python3 -mvenv $GITHUB_WORKSPACE/venv --system-site-packages
        bash -c "source $GITHUB_WORKSPACE/venv/bin/activate && pip3 install robotframework"

    - name: Run tests
      shell: bash
      run: |
        RSPAMD_INSTALLROOT=/usr bash -c "source $GITHUB_WORKSPACE/venv/bin/activate && robot --removekeywords wuks --exclude isbroken $GITHUB_WORKSPACE/rspamd/test/functional/cases"
