name: Test package

inputs:
  name:
    required: true
    type: string
  platform:
    required: true
    type: string
  run_id:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Download package
      uses: actions/download-artifact@v5
      with:
        name: packages-${{ inputs.platform }}-${{ inputs.name }}
        run_id: ${{ inputs.run_id }}
