name: Set version information to environment

runs:
  using: "composite"
  steps:
    - name: Set version information
      shell: bash
      run: |
        export RSPAMD_VERSION=`echo ${{ github.ref_name }} | sed s/^v// | sed 's/\+.*//'`
        echo "RSPAMD_VERSION=${RSPAMD_VERSION}" >> "$GITHUB_ENV"
        export RELEASE_VERSION=`echo ${{ github.ref_name }} | cut -d'+' -f2`
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> "$GITHUB_ENV"
