name: nightly

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: rspamd-packages-nightly

jobs:
  build_test:
    uses: ./.github/workflows/build_test.yml
    with:
      nightly: false
