name: Publish package (Debian)

on:
  workflow_call:
    inputs:
      names:
        required: true
        type: string
        description: 'The target distro names to publish (e.g. debian-trixie,debian-bookworm)'

jobs:
  test:
    name: 'publish (debian)'
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Download package
        run: |
          echo FIXME
