name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"
  workflow_dispatch:

concurrency:
  group: rspamd-packages-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build_packages:
    strategy:
      matrix:
        name: ['centos-8', 'centos-9', 'centos-10', 'debian-bullseye', 'debian-bookworm', 'debian-trixie', 'ubuntu-focal', 'ubuntu-jammy', 'ubuntu-noble']
        runner: ['ubuntu-24.04', 'ubuntu-24.04-arm']
    steps:
      build_packages:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "${{ matrix.name }}"
          runner: "${{ matrix.runner }}"
        permissions:
          packages: write
          contents: read
