name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"
  workflow_dispatch:

concurrency:
  group: rspamd-packages-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: {{ matrix.runner }}
    strategy:
      matrix:
        runner: ['ubuntu-24.04', 'ubuntu-24.04-arm']
    steps:
      packages_centos_8:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "centos-8"
        permissions:
          packages: write
          contents: read

      packages_centos_9:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "centos-9"
        permissions:
          packages: write
          contents: read

      packages_centos_10:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "centos-10"
        permissions:
          packages: write
          contents: read

      packages_debian_bullseye:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "debian-bullseye"
        permissions:
          packages: write
          contents: read

      packages_debian_bookworm:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "debian-bookworm"
        permissions:
          packages: write
          contents: read

      packages_debian_trixie:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "debian-trixie"
        permissions:
          packages: write
          contents: read

      packages_ubuntu_focal:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "ubuntu-focal"
        permissions:
          packages: write
          contents: read

      packages_ubuntu_jammy:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "ubuntu-jammy"
        permissions:
          packages: write
          contents: read

      packages_ubuntu_noble:
        uses: ./.github/workflows/build_packages.yml
        with:
          name: "ubuntu-noble"
        permissions:
          packages: write
          contents: read
