name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"
  workflow_dispatch:

concurrency:
  group: rspamd-packages-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build_packages:
    runs-on: "${{ matrix.runner }}"
    strategy:
      fail-fast: false
      matrix:
        name: ['centos-8', 'centos-9', 'centos-10', 'debian-bullseye', 'debian-bookworm', 'debian-trixie', 'ubuntu-focal', 'ubuntu-jammy', 'ubuntu-noble']
        runner: ['ubuntu-24.04', 'ubuntu-24.04-arm']
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build_packages
        id: build_packages
        with:
          name: "${{ matrix.name }}"

  test_package:
    needs: build_packages
    runs-on: "${{ matrix.runner }}"
    container:
      image: "${{ matrix.image }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-8
            image: oraclelinux:8
            runner: 'ubuntu-24.04'
          - name: centos-8
            image: oraclelinux:8
            runner: 'ubuntu-24.04-arm'
          - name: centos-9
            image: oraclelinux:9
            runner: 'ubuntu-24.04'
          - name: centos-9
            image: oraclelinux:9
            runner: 'ubuntu-24.04-arm'
          - name: centos-10
            image: oraclelinux:10
            runner: 'ubuntu-24.04'
          - name: centos-10
            image: oraclelinux:10
            runner: 'ubuntu-24.04-arm'
          - name: debian-bullseye
            image: debian:bullseye
            runner: 'ubuntu-24.04'
          - name: debian-bullseye
            image: debian:bullseye
            runner: 'ubuntu-24.04-arm'
          - name: debian-bookworm
            image: debian:bookworm
            runner: 'ubuntu-24.04'
          - name: debian-bookworm
            image: debian:bookworm
            runner: 'ubuntu-24.04-arm'
          - name: debian-trixie
            image: debian:trixie
            runner: 'ubuntu-24.04'
          - name: debian-trixie
            image: debian:trixie
            runner: 'ubuntu-24.04-arm'
          - name: ubuntu-focal
            image: ubuntu:20.04
            runner: 'ubuntu-24.04'
          - name: ubuntu-focal
            image: ubuntu:20.04
            runner: 'ubuntu-24.04-arm'
          - name: ubuntu-jammy
            image: ubuntu:22.04
            runner: 'ubuntu-24.04'
          - name: ubuntu-jammy
            image: ubuntu:22.04
            runner: 'ubuntu-24.04-arm'
          - name: ubuntu-noble
            image: ubuntu:24.04
            runner: 'ubuntu-24.04'
          - name: ubuntu-noble
            image: ubuntu:24.04
            runner: 'ubuntu-24.04-arm'
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/test_package
        with:
          name: "${{ matrix.name }}"
          platform: "${{ runner.arch }}"
          run_id: "${{ steps.build_packages.outputs.run_id }}"
