name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"
  workflow_dispatch:

concurrency:
  group: rspamd-packages-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build_packages:
    runs-on: "${{ matrix.runner }}"
    strategy:
      fail-fast: false
      matrix:
        name: ['centos-8', 'centos-9', 'centos-10', 'debian-bullseye', 'debian-bookworm', 'debian-trixie', 'ubuntu-focal', 'ubuntu-jammy', 'ubuntu-noble']
        runner: ['ubuntu-24.04', 'ubuntu-24.04-arm']
    steps:
      - name: Determine base image
        id: base_image
        run: |
          case "${{ matrix.name }}" in
            centos-8) echo "image=oraclelinux:8" >> $GITHUB_OUTPUT ;;
            centos-9) echo "image=oraclelinux:9" >> $GITHUB_OUTPUT ;;
            centos-10) echo "image=oraclelinux:10" >> $GITHUB_OUTPUT ;;
            debian-bullseye) echo "image=debian:bullseye" >> $GITHUB_OUTPUT ;;
            debian-bookworm) echo "image=debian:bookworm" >> $GITHUB_OUTPUT ;;
            debian-trixie) echo "image=debian:trixie" >> $GITHUB_OUTPUT ;;
            ubuntu-focal) echo "image=ubuntu:20.04" >> $GITHUB_OUTPUT ;;
            ubuntu-jammy) echo "image=ubuntu:22.04" >> $GITHUB_OUTPUT ;;
            ubuntu-noble) echo "image=ubuntu:24.04" >> $GITHUB_OUTPUT ;;
            *) echo "Can't determine proper base image for ${{ matrix.name }}" >&2; exit 1 ;;
          esac

      - uses: actions/checkout@v4

      - uses: ./.github/actions/build_packages
        id: build_packages
        with:
          name: "${{ matrix.name }}"

      - uses: ./.github/actions/test_package
        with:
          base_image: "${{ steps.base_image.outputs.image }}"
          name: "${{ matrix.name }}"
          run_id: "${{ steps.build_packages.outputs.run_id }}"
