name: Test Retention Logic
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the workflow run to get packages from'
        required: true
        type: string
      nightly:
        description: 'Set to "y" to simulate a nightly run'
        required: false
        type: string
        default: 'y'

jobs:
  centos-8-build-X64:
    name: Download centos-8 X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-centos-8-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-centos-8-X64
          path: artifact/
  centos-8-build-ARM64:
    name: Download centos-8 ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-centos-8-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-centos-8-ARM64
          path: artifact/

  centos-9-build-X64:
    name: Download centos-9 X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-centos-9-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-centos-9-X64
          path: artifact/
  centos-9-build-ARM64:
    name: Download centos-9 ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-centos-9-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-centos-9-ARM64
          path: artifact/

  centos-10-build-X64:
    name: Download centos-10 X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-centos-10-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-centos-10-X64
          path: artifact/
  centos-10-build-ARM64:
    name: Download centos-10 ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-centos-10-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-centos-10-ARM64
          path: artifact/

  debian-bookworm-build-X64:
    name: Download debian-bookworm X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-debian-bookworm-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-debian-bookworm-X64
          path: artifact/
  debian-bookworm-build-ARM64:
    name: Download debian-bookworm ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-debian-bookworm-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-debian-bookworm-ARM64
          path: artifact/

  debian-bullseye-build-X64:
    name: Download debian-bullseye X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-debian-bullseye-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-debian-bullseye-X64
          path: artifact/
  debian-bullseye-build-ARM64:
    name: Download debian-bullseye ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-debian-bullseye-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-debian-bullseye-ARM64
          path: artifact/

  debian-trixie-build-X64:
    name: Download debian-trixie X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-debian-trixie-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-debian-trixie-X64
          path: artifact/
  debian-trixie-build-ARM64:
    name: Download debian-trixie ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-debian-trixie-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-debian-trixie-ARM64
          path: artifact/

  ubuntu-focal-build-X64:
    name: Download ubuntu-focal X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-ubuntu-focal-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-ubuntu-focal-X64
          path: artifact/
  ubuntu-focal-build-ARM64:
    name: Download ubuntu-focal ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-ubuntu-focal-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-ubuntu-focal-ARM64
          path: artifact/

  ubuntu-jammy-build-X64:
    name: Download ubuntu-jammy X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-ubuntu-jammy-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-ubuntu-jammy-X64
          path: artifact/
  ubuntu-jammy-build-ARM64:
    name: Download ubuntu-jammy ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-ubuntu-jammy-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-ubuntu-jammy-ARM64
          path: artifact/

  ubuntu-noble-build-X64:
    name: Download ubuntu-noble X64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-ubuntu-noble-X64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-ubuntu-noble-X64
          path: artifact/
  ubuntu-noble-build-ARM64:
    name: Download ubuntu-noble ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download ${{ inputs.run_id }} -n packages-ubuntu-noble-ARM64 -p artifact
      - name: Upload package for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: packages-ubuntu-noble-ARM64
          path: artifact/

  centos-8-publish:
    name: Test Publish centos-8
    needs: [centos-8-build-X64, centos-8-build-ARM64]
    secrets: inherit
    uses: ./.github/workflows/publish_rpm.yml
    with:
      name: centos-8
      nightly: ${{ inputs.nightly }}

  centos-9-publish:
    name: Test Publish centos-9
    needs: [centos-9-build-X64, centos-9-build-ARM64]
    secrets: inherit
    uses: ./.github/workflows/publish_rpm.yml
    with:
      name: centos-9
      nightly: ${{ inputs.nightly }}

  centos-10-publish:
    name: Test Publish centos-10
    needs: [centos-10-build-X64, centos-10-build-ARM64]
    secrets: inherit
    uses: ./.github/workflows/publish_rpm.yml
    with:
      name: centos-10
      nightly: ${{ inputs.nightly }}

  debian-publish:
    name: Test Publish debian
    needs:
      - debian-bookworm-build-X64
      - debian-bookworm-build-ARM64
      - debian-bullseye-build-X64
      - debian-bullseye-build-ARM64
      - debian-trixie-build-X64
      - debian-trixie-build-ARM64
      - ubuntu-focal-build-X64
      - ubuntu-focal-build-ARM64
      - ubuntu-jammy-build-X64
      - ubuntu-jammy-build-ARM64
      - ubuntu-noble-build-X64
      - ubuntu-noble-build-ARM64
    secrets: inherit
    uses: ./.github/workflows/publish_deb.yml
    with:
      names: debian-bookworm,debian-bullseye,debian-trixie,ubuntu-focal,ubuntu-jammy,ubuntu-noble
      nightly: ${{ inputs.nightly }}
