# to rather not wait for builds
name: test

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true

jobs:
  test_package:
    permissions:
      actions: read
    runs-on: "${{ matrix.runner }}"
    container:
      image: "${{ matrix.image }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-8
            image: oraclelinux:8
            runner: 'ubuntu-24.04'
          - name: centos-8
            image: oraclelinux:8
            runner: 'ubuntu-24.04-arm'
          - name: centos-9
            image: oraclelinux:9
            runner: 'ubuntu-24.04'
          - name: centos-9
            image: oraclelinux:9
            runner: 'ubuntu-24.04-arm'
          - name: centos-10
            image: oraclelinux:10
            runner: 'ubuntu-24.04'
          - name: centos-10
            image: oraclelinux:10
            runner: 'ubuntu-24.04-arm'
          - name: debian-bullseye
            image: debian:bullseye
            runner: 'ubuntu-24.04'
          - name: debian-bullseye
            image: debian:bullseye
            runner: 'ubuntu-24.04-arm'
          - name: debian-bookworm
            image: debian:bookworm
            runner: 'ubuntu-24.04'
          - name: debian-bookworm
            image: debian:bookworm
            runner: 'ubuntu-24.04-arm'
          - name: debian-trixie
            image: debian:trixie
            runner: 'ubuntu-24.04'
          - name: debian-trixie
            image: debian:trixie
            runner: 'ubuntu-24.04-arm'
          - name: ubuntu-focal
            image: ubuntu:20.04
            runner: 'ubuntu-24.04'
          - name: ubuntu-focal
            image: ubuntu:20.04
            runner: 'ubuntu-24.04-arm'
          - name: ubuntu-jammy
            image: ubuntu:22.04
            runner: 'ubuntu-24.04'
          - name: ubuntu-jammy
            image: ubuntu:22.04
            runner: 'ubuntu-24.04-arm'
          - name: ubuntu-noble
            image: ubuntu:24.04
            runner: 'ubuntu-24.04'
          - name: ubuntu-noble
            image: ubuntu:24.04
            runner: 'ubuntu-24.04-arm'
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/test_package
        with:
          name: "${{ matrix.name }}"
          platform: "${{ runner.arch }}"
          run_id: "${{ inputs.run_id }}"
